### ISSUE TITLE
Working day description not sent

### ISSUE THREAD

**Issue by manedev79** [manedev79/timesheet-ui#6]
It seems like the working day description is not correctly sent to the backend:

UI:
![grafik](https://user-images.githubusercontent.com/43153222/48866511-597c4980-edd3-11e8-8138-b0e00425aeb7.png)

REST Controller:
![grafik](https://user-images.githubusercontent.com/43153222/48866524-6436de80-edd3-11e8-83f2-6a655fcb7ea4.png)

Note: This might as well be a bug in the backend component

**Comment by JanLoebel** [comment]
Closed with #7
